import { useCallback } from 'react';
import '../animations/reveal.css';

/**
 * One observer for the whole document.
 *
 * Created on first use and never torn down — the alternative is 106 observers,
 * one per reveal, each with its own root, margin and threshold list to evaluate
 * against every scroll. A single shared instance evaluates one geometry set per
 * frame regardless of how many elements are registered.
 *
 * The margin fires the transition slightly before the element is fully on
 * screen, so content is already resolved by the time the reader's eye arrives
 * rather than animating under it — the same `amount: 0.18` / `-12%` framing the
 * framer-motion viewport config used.
 */
let observer = null;

/** Share of the element that must be on screen before it is revealed. */
const AMOUNT = 0.18;

/**
 * Share of the *viewport* an element must fill to count as arrived, regardless
 * of its own size.
 *
 * An element taller than the root can never reach `AMOUNT` of itself: a 5,000px
 * panel needs 900px on screen to hit 18%, and a phone has 844px to give. Without
 * this it stays hidden forever, which is precisely the failure mode below.
 */
const ROOT_FILL = 0.35;

/**
 * Marks an element revealed.
 *
 * The state goes on a `data-revealed` attribute, **not** on a class, and that
 * distinction is load-bearing.
 *
 * `className` belongs to React. These elements are MUI components whose class
 * is generated by Emotion from their `sx` prop, so any re-render that changes
 * `sx` produces a new class and React writes the whole `className` attribute
 * again — silently discarding a class added imperatively from here. The result
 * is a section that reveals correctly and then vanishes the moment anything
 * makes it re-render: the ecosystem diagram's industry cards disappeared on
 * hover, because hovering changes their border and background, and the
 * allocation meters collapsed to zero width for the same reason.
 *
 * React only writes attributes it renders. `data-revealed` appears in no JSX, so
 * React never touches it and the reveal survives every re-render.
 */
function reveal(el, instant) {
  el.setAttribute('data-revealed', instant ? 'instant' : '');
  observer.unobserve(el);
}

function getObserver() {
  if (observer || typeof IntersectionObserver === 'undefined') return observer;
  observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        const root = entry.rootBounds;

        /*
         * ── The safety net ───────────────────────────────────────────────
         *
         * If the element is above the viewport we have already scrolled past
         * it, and whatever should have triggered its entrance did not. Show it
         * — without the entrance, because an element fading in behind the
         * reader is worse than one that was simply already there.
         *
         * This is not hypothetical. The live site ships this bug: 17 blocks of
         * copy on a phone and 35 on a desktop stayed at `opacity: 0` while
         * fully on screen, and a visitor scrolling the page found blank bands
         * where the features grid, the industries list and the compliance
         * register should have been.
         *
         * The cause is `content-visibility: auto`, which is otherwise the best
         * thing on this page. A skipped section has no layout boxes, so its
         * contents are reported as not intersecting and are invisible to the
         * observer. By the time the section is rendered the reader may already
         * be level with it, and the entrance condition — a share of the element
         * on screen, measured from below — was met during the frames when there
         * was nothing to measure. It never fires, and the copy never appears.
         *
         * Widening the trigger (below) closes most of the gap; this closes the
         * rest, and does so for any future cause as well, because it keys off
         * the only thing that actually matters: the reader can see it and it is
         * not visible.
         */
        if (!entry.isIntersecting) {
          if (entry.boundingClientRect.bottom <= (root?.top ?? 0)) reveal(entry.target, true);
          continue;
        }

        const filled = root?.height ? entry.intersectionRect.height / root.height : 1;
        if (entry.intersectionRatio >= AMOUNT || filled >= ROOT_FILL) reveal(entry.target, false);
      }
    },
    {
      /*
       * Both thresholds are needed. `AMOUNT` is the one the design is tuned to;
       * `0` guarantees a callback on the way in and on the way out, which is
       * what gives the safety net above a chance to run for an element that
       * never satisfies `AMOUNT` at any sampled frame — the case a fast scroll
       * through freshly un-skipped content produces.
       */
      threshold: [0, AMOUNT],
      rootMargin: '0px 0px -12% 0px',
    },
  );
  return observer;
}

/**
 * Returns a ref callback that registers a node with the shared observer.
 *
 * Pair it with a `data-reveal` attribute — or with `.ef-meter` / `.ef-arc`,
 * which key off the same `data-revealed` attribute — and, if needed, the `--rv-*`
 * custom properties. One callback can serve any number of elements, so a
 * component that already renders the element it wants revealed can opt in
 * without a wrapper `<div>` between it and its parent's layout.
 *
 * ── Why this does not measure anything ───────────────────────────────────
 *
 * The obvious implementation asks each node "am I already on screen?" with
 * `getBoundingClientRect()`, so that content the reader is already looking at —
 * after a deep link to an anchor, say — is revealed outright instead of waiting
 * a frame for the observer.
 *
 * That question is far more expensive than it looks. Asked from inside a React
 * commit it flushes layout for the whole document on every call; batched into
 * one animation frame it flushes once per batch, but the reveal marks written
 * written straight afterwards invalidate that layout, so the frame pays for two
 * full passes over a 30,000px document instead of one. Both shapes were measured
 * on this page: 946ms and 889ms respectively, in each case the single largest
 * cost in the entire load.
 *
 * The observer already computes exactly this, during the frame's own lifecycle,
 * at no additional cost — an element that is on screen when it is observed is
 * reported as intersecting at the next rendering opportunity. That is one frame
 * later than measuring, and one frame of an element sitting at `opacity: 0`
 * before a 900ms fade begins is not a thing anyone can see.
 *
 * So: observe, and let the browser answer.
 */
export default function useReveal() {
  return useCallback((node) => {
    if (!node) return undefined;

    const io = getObserver();
    if (!io) {
      node.setAttribute('data-revealed', '');
      return undefined;
    }

    io.observe(node);
    /* React 19 calls a ref callback's return value on detach, which is what lets
       one callback serve every element in a `.map()` — each node cleans up after
       itself rather than the hook tracking "the last one". */
    return () => io.unobserve(node);
  }, []);
}

export { useReveal };
